<?php

class AcfClass
{
    public function __construct()
	{
        add_action('admin_menu',		array('AcfClass', 'createOptionsPage'));
        add_action('init',				array('AcfClass', 'defaultOptions'));
    }

	// Create options page on admin
	public static function createOptionsPage()
	{
		if( function_exists('acf_add_options_page') ) {

			$parent = acf_add_options_page(array(
				'page_title' 	=> 'Opções',
				'menu_title' 	=> 'Opções',
				'menu_slug' 	=> 'options',
                'redirect'      => false,
				'position'      => '2.3'
			));

		}
	}

	// Code generated by Advanced Custom Fields
	// If you want a blank options page, just delete below. 
	public static function defaultOptions()
	{
		if( function_exists('acf_add_local_field_group') ):

			acf_add_local_field_group(array(
				'key' => 'group_6027197ae779a',
				'title' => 'Configurações Gerais',
				'fields' => array(
					array(
						'key' => 'field_602719a371bf0',
						'label' => 'Geral',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_6027198b71bef',
						'label' => 'Logotipo',
						'name' => 'logotipo',
						'type' => 'image',
						'instructions' => 'A logo do seu site, suba a imagem com melhor qualidade possível. Recomendamos que seja em SVG ou PNG. Tamanho máximo de 5mb.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => 5,
						'mime_types' => '',
					),
					array(
						'key' => 'field_602719b571bf1',
						'label' => 'Favicon',
						'name' => 'favicon',
						'type' => 'image',
						'instructions' => 'O Favicon do seu site, ele é o ícone que fica na barra do navegador. Ele precisa ter a medida de 128x128. Recomendamos que seja em PNG. Tamanho máximo de 1mb.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => 1,
						'mime_types' => '',
					),
					array(
						'key' => 'field_60271af9345d0',
						'label' => 'Slogan',
						'name' => 'slogan',
						'type' => 'text',
						'instructions' => 'Caso tenha, o slogan do seu site.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60271b17ac2a3',
						'label' => 'Cor Principal',
						'name' => 'cor_principal',
						'type' => 'color_picker',
						'instructions' => 'A cor principal que define o seu site.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
					),
					array(
						'key' => 'field_60271bbce0181',
						'label' => 'Endereço Fixo',
						'name' => 'endereco_fixo',
						'type' => 'text',
						'instructions' => 'Ex: Rua de exemplo, 1180 - CEP, Cidade - Estado',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60271b4e1c43d',
						'label' => 'Horário de Atendimento',
						'name' => 'horario_de_atendimento',
						'type' => 'text',
						'instructions' => 'Ex: Segunda a sexta, das 08:00 às 18h. Sábados das 08:30 às 13h.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60271b5b1c43e',
						'label' => 'Telefone Principal',
						'name' => 'telefone_principal',
						'type' => 'text',
						'instructions' => 'Ex: 41 99999-9999',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60271b6b1c43f',
						'label' => 'Telefone Secundário',
						'name' => 'telefone_secundario',
						'type' => 'text',
						'instructions' => 'Ex: 41 99999-9999',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60271bfbbd37f',
						'label' => 'Número de Whatsapp',
						'name' => 'numero_de_whatsapp',
						'type' => 'text',
						'instructions' => 'Ex: 41 99999-9999',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60271c2e647b5',
						'label' => 'Email para contato',
						'name' => 'email_para_contato',
						'type' => 'email',
						'instructions' => 'Ex: contato@exemplo.com.br',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_60271c8bb1fb0',
						'label' => 'Social',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_60271c91b1fb1',
						'label' => 'Rede Sociais',
						'name' => 'rede_sociais',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => 'Adicionar Rede',
						'sub_fields' => array(
							array(
								'key' => 'field_60271ca8b1fb2',
								'label' => 'Nome',
								'name' => 'nome',
								'type' => 'text',
								'instructions' => 'Ex: Facebook, Instagram, Linkedin, Twitter e etc.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_60271cc8b1fb3',
								'label' => 'URL',
								'name' => 'url',
								'type' => 'url',
								'instructions' => 'Ex: https://facebook.com',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'options_page',
							'operator' => '==',
							'value' => 'options',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));
			
			endif;
	}
}

new AcfClass();